### ISSUE TITLE
go live

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/xcompat#1]
* [x] list on cdb
* [x] [homedecor](https://github.com/mt-mods/homedecor_modpack/pull/63)
* [x] [basic materials](https://github.com/mt-mods/basic_materials/pull/25)
* [x] [steel](https://github.com/mt-mods/steel/pull/5)
* [x] [pipeworks](https://github.com/mt-mods/pipeworks/pull/113)
* [x] [dreambuilder](https://github.com/mt-mods/dreambuilder_game/pull/501) - adding this mod
* [x] any other mods???
* [x] transfer https://github.com/mt-mods/xcompat/issues/8 to this repo
* [x] point to here and archive https://github.com/mt-mods/sound_api_core
* [x] point to here and archive https://github.com/mt-mods/sound_api
* [x] profit?

**Comment by S-S-X** [comment]
Maybe also add simple short simple instructions to update from sound_api unless you know sound_api were only used by just very few mods / mods where you're sure devs know how.

**Comment by wsor4035** [comment]
> Maybe also add short simple instructions to update from sound_api unless you know sound_api were only used by just very few mods / mods where you're sure devs know how.

im planning on making prs to all the existing repos

**Comment by Lazerbeak12345** [comment]
In the Whynot? game, there weren't more than 2 or 3, so I doubt you've got very many PRs to make in total.

**Comment by wsor4035** [comment]
> In the Whynot? game, there weren't more than 2 or 3, so I doubt you've got very many PRs to make in total.

not my problem to update yalls mods (assuming not misunderstanding something here)

**Comment by Lazerbeak12345** [comment]
Yep we're on the same page. I agree. Just confirming something you said earlier.

**Comment by wsor4035** [comment]
last pr made, other things taken care of, closing this
