### ISSUE TITLE
create boot up minetest tests for mods that use xcompat

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/xcompat#14]
see title, like dreambuilder

* [x] basic materials
* [x] steel
* [x] pipeworks
* [x] display modpack
* [x] homedecor

for the following games
* [x] minetest game
* [x] farlands reloaded
* [x] mineclonia
* [x] mineclone2
* [x] hades

**Comment by Kazooo100** [comment]
What does this do exactly?

**Comment by wsor4035** [comment]
runs a minetest server in ci to make sure it doesnt crash, etc
