### ISSUE TITLE
PR #22 partly reverted the fix for issue #20

### ISSUE THREAD

**Issue by j-r** [mt-mods/xcompat#26]
mcl jungle tree leaves again use the wrong item string instead of ``"mcl_trees:leaves_jungle"``

**Comment by Niklp09** [comment]
https://github.com/mt-mods/xcompat/issues/20 (link for lazy people like me)

**Comment by wsor4035** [comment]
it was https://github.com/mt-mods/xcompat/pull/21/files actually

**Comment by j-r** [comment]
Yeah, I'm sorry I mixed that up. Didn't want to point in the wrong direction.

Thanks for fixing it so fast!

**Comment by wsor4035** [comment]
np
