### ISSUE TITLE
Sound Api Broken for MTG derivatives after refactor

### ISSUE THREAD

**Issue by Kazooo100** [mt-mods/xcompat#28]
Sound Api, and potentially other stuff, broken for MTG derivatives, including mesecraft, after refactor.

Before refactor a block using xcompat wood/glass sounds would have wood/glass sounds, after they have no sound.

**Comment by wsor4035** [comment]
![image](https://github.com/mt-mods/xcompat/assets/24964441/8e7e01aa-29e6-4f8a-944d-01aafba45587)
appears to be working

**Comment by wsor4035** [comment]
![image](https://github.com/mt-mods/xcompat/assets/24964441/65fd79eb-0307-4591-acd6-89fa7c0af260)

**Comment by Kazooo100** [comment]
is that mesecraft or? Do you hear the sounds? I didnt with same block with old xcompat and new

**Comment by Kazooo100** [comment]
[Screen Recordings.zip](https://github.com/mt-mods/xcompat/files/15477389/Screen.Recordings.zip)
Here are some recordings. This is a test node. As you can hear the sounds are different between the 2. 
Here is the test nodes code aswell
`        minetest.register_node("willow:willow_planks", {
            description = "Willow",
            paramtype2 = "facedir",
            place_param2 = 0,
            tiles = {"willow_planks.png"},
            is_ground_content = false,
            groups = {choppy = 2, oddly_breakable_by_hand = 2, flammable = 2, wood = 1,
            --mcl groups below, minetest above
            handy = 1, axey = 1, material_wood = 1, fire_encouragement = 5, fire_flammability = 20,
		--farlands reload groups below
		dig_tree = 2, wood_related = 1, plank = 1, stairable = 1},
--fenceable = 1,
            --mcl is flammable 3 default is 2
            sounds = xcompat.sounds.node_sound_wood_defaults(),
        })
`

**Comment by Kazooo100** [comment]
Hey just wondering if anyone played the recordings? If needed I can attempt to record in different format or something?

**Comment by wsor4035** [comment]
tested on mtg stock 5.8

![image](https://github.com/mt-mods/xcompat/assets/24964441/f36fc6a3-6e94-4a35-979e-a0d8274c0ee3)

**Comment by wsor4035** [comment]
other than keys being in a different order, same results

**Comment by Kazooo100** [comment]
Looks same in your test image, what game is that?
Its weird in mesecraft/my videos place sound after refactor is very muted if ran at all.
Does it sound the same in your test/game?

**Comment by wsor4035** [comment]
sample mod i threw together

init.lua
```lua
minetest.register_node(":xcompat_wood_sound", {
    tiles = {xcompat.textures.gravel},
    groups = {oddly_breakable_by_hand = 3},
    sounds = xcompat.sounds.node_sound_wood_defaults(),
})

minetest.register_node(":xcompat_glass_sound", {
    tiles = {xcompat.textures.brick},
    groups = {oddly_breakable_by_hand = 3},
    sounds = xcompat.sounds.node_sound_glass_defaults(),
})
```

mod.conf
```
depends = xcompat
```

i can observe no difference

**Comment by Kazooo100** [comment]
Posting discord convo here for context.
Ok I did some more testing with your test mod.
I believe it is an issue with games based on mtg specifically because it works fine in mtg but does indeed still sound wrong in mesecraft.

 Also, the textures are wrong/different in mesecraft before and after refactor. Before refactor wood test used gravel texture and glass test used brick textures as intended after they both use solid textures.
 
I have some additional recordings, but cant upload them. Minetest game was restarted between each filming. 

Chucking ` if minetest.get_modpath("default") then gameid = "minetest" end` here: https://github.com/mt-mods/xcompat/blob/master/src/gameid.lua#L29 like wsor suggested in discord fixed it.
