### ISSUE TITLE
37a7fd6cc8ddc9eb303a2e66e27f9d3c21de7cfb breaks detection of voxelgarden used by moretrees

### ISSUE THREAD

**Issue by j-r** [mt-mods/xcompat#29]
The above mentioned commit just overrides the detected gameid with ``minetest`` when a mod named ``default`` exists.

Voxelgarden is not based on MTG, but compatible on a technical level, having a ``default`` mod and providing most of MTG's apis.

The reason moretrees wants to detect Voxelgarden is that it has different (higher level) gameplay mechanics, affecting out of the box experience of moretrees (see https://github.com/mt-mods/moretrees/pull/38 and https://github.com/mt-mods/moretrees/pull/40 for details).

OTOH it is probably useful for xcompat to detect Voxelgarden as a minetest game derivative because of its low level compatibility usually not requiring mods to do anything special.

I propose to enhance xcompat to provide the actual game id (if provided by new enough minetest) in addition to the detected compatibility game id.

**Comment by wsor4035** [comment]
i think its better for moretrees to just check itself, and only support that feature for minetest (whatever version added game detection).

**Comment by wsor4035** [comment]
`type(minetest.get_game_info) == "function" and minetest.get_game_info().id~="voxelgarden" or true` to replace https://github.com/mt-mods/moretrees/blob/master/settings.lua#L53 ~~assuming the logic passes, didnt check~~ one line fix and also makes a lot more sense than the pr (in my opinion) which makes a mess of things
