### ISSUE TITLE
avoid relying on `core.get_game_info().id` for detecting game kind

### ISSUE THREAD

**Issue by programmerjake** [mt-mods/xcompat#47]
it is quite annoying when you want multiple versions of the same game installed at once by giving the game folders different names, so e.g. if the game folder you tested with isn't named "mineclonia" exactly, then xcompat will decide it doesn't know what game you're using and give you all the `default:*` items. so, if you tested with your game folder named `mineclonia_git` like I did, then it'll break.

I think using `core.get_game_info().id` is still useful, but only as a last-resort fallback when probing for mod names doesn't succeed.

**Comment by wsor4035** [comment]
this is unsupported behavior

**Comment by programmerjake** [comment]
ok, though by rejecting this you're making game development more annoying...

**Comment by wsor4035** [comment]
no, its called using git

**Comment by programmerjake** [comment]
well, afaict I'm not the only one who ran into this, deducing from the giant list of `default:*` items, xXx_GLOCKrzmitz_xXx also ran into this issue: https://codeberg.org/mineclonia/mineclonia/issues/2311#issuecomment-2472523

also, sometimes you want the contentdb version installed alongside a git version. the contentdb version isn't the same as any git version due to the changes made by contentdb, plus contentdb having more automated updates.

**Comment by SwissalpS** [comment]
Symlinks exist and can work quite well for testing various versions from different sources.

My sympathies, though.
