### ISSUE TITLE
Avoid using the global keyword `table` as a function argument name

### ISSUE THREAD

**Issue by dacmot** [mt-mods/xcompat#5]
In the file [sounds.lua](https://github.com/mt-mods/xcompat/blob/master/src/sounds.lua), many functions use `table` as an argument name. Since `table` is also a global variable, it ends up being shadowed or redefined locally. This is generally regarded as a poor programming practice as it can be confusing what `table` is referring to.

**Comment by OgelGames** [comment]
I'm surprised luacheck didn't complain about that 🤔
