### ISSUE TITLE
Add texture API

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/xcompat#7]
Many (homedecor, display_modpack, etc.) mods depend on special game textures e.g. `default_wood.png`. It would make sense to have some kind of gamecompat here.

Propsal:
Just add a `xcompat.textures.$texturename` table, `$texturename`s should be the same as for `xcompat.materials`.

**Comment by OgelGames** [comment]
I don't think they should be grouped, it doesn't make using it any easier, and it doesn't make sense for a lot of nodes that only have one texture.

**Comment by wsor4035** [comment]
Lazerbeak12345: i would recommend making a new issue for ui/ux textures or something, this and the linked pr is mostly for unify duplicated code we have in other mods already
